logging:
  level:
    org.springframework.boot: ERROR

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"




spring:
  http:
    codecs:
      log-request-details: true
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL
          mock-movie-service:
            url: http://localhost:9090
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: FULL
            errorDecoder: com.openfeign.client.error.MovieClientErrorDecoder


resilience4j.retry:
  instances:
    movieServiceRetryOnException:
      maxAttempts: 4
      waitDuration: 3s
      retryExceptions:
        - com.openfeign.exception.MovieInternalServerException
      ignoreExceptions:
        - com.openfeign.exception.MovieNotFoundException

