logging:
  level:
    org.springframework.boot: ERROR

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

movie-mock-service:
    endpoint: http://localhost:8080

spring:
  http:
    codecs:
      log-request-details: true




